name: lace/stage2
stage: 2
dataset:
  data_dir: data/textile
  class_name: lace
  batch_size: 4
  num_workers: 8
model:
  backbone: wide_resnet50_2
  pool_type: avg
  parallel_blocks:
    - 2
    - 5
    - 8
  c_conds:
    - 64
    - 64
    - 64
  clamp_alpha: 1.9
mode: train
model_path: outputs/lace/stage1/best_loss_model.pth
train:
  epochs: 200
  optim:
    lr: 2e-5
  output_dir: outputs